apiVersion: v1
kind: ConfigMap
metadata:
  name: demoapi-config
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",

      "Settings": {
        "Message": "Hello from the k8's appsettings file"
      }
    }
